name: Deploy React to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: "react-distribute-bucket-ky-cloudfront-bucket-quiz-distributor"
    permissions:
      id-token: write   # OIDCで必要
      contents: read    # checkoutで必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ env.S3_BUCKET }} --delete